-- game_code is required, so backfill existing games with a random code before
-- adding the NOT NULL constraint. Generated by drizzle-kit, then hand-edited.
ALTER TABLE "games" ADD COLUMN "game_code" text;--> statement-breakpoint
UPDATE "games" SET "game_code" = upper(translate(substr(md5(random()::text || id), 1, 6), '01il', 'WXYZ')) WHERE "game_code" IS NULL;--> statement-breakpoint
ALTER TABLE "games" ALTER COLUMN "game_code" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "games" ADD COLUMN "allow_self_signup" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "games" ADD COLUMN "allow_team_creation" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "games" ADD COLUMN "allow_team_names" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "games" ADD COLUMN "allow_team_photos" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "games" ADD COLUMN "route_signup_enabled" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "games" ADD COLUMN "wildcard_enabled" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "games" ADD COLUMN "wildcard_name" text;--> statement-breakpoint
ALTER TABLE "games" ADD COLUMN "staggered_start" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "games" ADD COLUMN "qr_remove_by" timestamp;--> statement-breakpoint
ALTER TABLE "games" ADD COLUMN "issue_contact_phone" text;--> statement-breakpoint
ALTER TABLE "games" ADD CONSTRAINT "games_game_code_unique" UNIQUE("game_code");
